"""added user columns

Revision ID: 75179f2d9e73
Revises: cbc313ffc2a8
Create Date: 2024-07-04 11:10:22.490217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75179f2d9e73'
down_revision = 'cbc313ffc2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
