"""Added number of likes

Revision ID: c9fc2f19ad34
Revises: b532f85581ab
Create Date: 2024-07-11 12:13:33.196712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fc2f19ad34'
down_revision = 'b532f85581ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('number_of_likes')

    # ### end Alembic commands ###
